### ISSUE TITLE
Adding C++ or Python Solution 

### ISSUE THREAD

**Issue by bishalshaw-164** [Shubhanshu-1507/Sourcecode#141]
I would like add question and solution of c++ or Python. Could you please assign this issue to me for Hacktoberfest 2024

**Comment by AnshDwivedi03** [comment]
Can i contribute

**Comment by rahul-chakradhari** [comment]
@Shubhanshu-1507  can  i add 2d array questions from c++ language i had also answers with proper explaination
please assign to me also

**Comment by Shubhanshu-1507** [comment]
> @Shubhanshu-1507  can  i add 2d array questions from c++ language i had also answers with proper explaination
> please assign to me also also add all the labels required

Ofcourse 👍

**Comment by rahul-chakradhari** [comment]
assign this task to em with proper labels @Shubhanshu-1507

**Comment by eeshsaxena** [comment]
Assign me this issue i will do it.
