### ISSUE TITLE
Add Java Searching and Sorting Algorithms

### ISSUE THREAD

**Issue by DevDatir** [Shubhanshu-1507/Sourcecode#151]
I want to contribute to this repository by adding implementations of various searching and sorting algorithms in Java. Can you assign me to this issue|

**Comment by Arushigupta04** [comment]
can i write code for seaching sorting

**Comment by AnshDwivedi03** [comment]
Can you assign it to me

**Comment by Dhiraj1732** [comment]
i want to contribute will you assign it to me
