### ISSUE TITLE
Sorting algorithms

### ISSUE THREAD

**Issue by Speedysays01** [Shubhanshu-1507/Sourcecode#174]
Please assign me this issue under Hacktoberfest 2024!
I can add  a folder with sorting algorithms like Bubble sort, Merge sort, Selection sort etc with their information and algorithms in readme.md.

**Comment by AnshDwivedi03** [comment]
Hey @Shubhanshu-1507 can you asiign it to me.. I want more detail.. You want complete sort functions or you want specific

**Comment by Ankurcr7** [comment]
Hey @Shubhanshu-1507,
Can you assign me to this issue.

**Comment by PRAVIVEK** [comment]
hey @Shubhanshu-1507 can you assign it to me !

**Comment by hoshangchakravarty** [comment]
Hey 👋! Could you please assign me this? I will add heap sort, quick sort, etc with their full explanations and time complexity

**Comment by KartikMouli** [comment]
Hey @Shubhanshu-1507  ,Could you please assign me this? I can add shellsort,bucketsort,heapsort, and radixsort in cpp

**Comment by eeshsaxena** [comment]
Assign me this issue i will do it.

**Comment by K155jadhav** [comment]
Hi, I am Kanchan Jadhav. Could you please assign this issue to me?

**Comment by Sanskruti36** [comment]
Hello, I am Sanskruti Patil from Second Year Comp.
Could you please assign this issue to me?
