### ISSUE TITLE
Java Searching Algorithms

### ISSUE THREAD

**Issue by Sahil-xyz** [Shubhanshu-1507/Sourcecode#186]
Hello @Shubhanshu-1507 ,
I would like to implement Searching algroithms using java in java folder.
(i) Linear Search 
(ii) Binary Search
Kindly assign me this issue under hacktoberfest and hacktoberfest-accepted.

**Comment by K155jadhav** [comment]
Hi, I am Kanchan Jadhav. Could you please assign this issue to me?

**Comment by Sanskruti36** [comment]
Hello, I am Sanskruti Patil from Second Year.
Could you please assign this issue to me?
