### ISSUE TITLE
Adding Basic Algorithms for C.

### ISSUE THREAD

**Issue by Prem-Kumar-Dev** [Shubhanshu-1507/Sourcecode#188]
I would like to contribute to this repository by adding algorithm implementations in C as part of Hacktoberfest 2024.

**Comment by Prem-Kumar-Dev** [comment]
Kindly add hacktober2024 label.

**Comment by Prem-Kumar-Dev** [comment]
@Shubhanshu-1507 Added basic C algorithms. Kindly review and give hacktoberfest2024-accepted label

**Comment by eeshsaxena** [comment]
Assign me this issue i will do it.

**Comment by Prem-Kumar-Dev** [comment]
@eeshsaxena @Shubhanshu-1507 already done
