### ISSUE TITLE
Proposal : Implementing M - Coloring Problem

### ISSUE THREAD

**Issue by AbhijitMotekar99** [Shubhanshu-1507/Sourcecode#193]
Problem Statement: Given an undirected graph and a number m, determine if the graph can be colored with at most m colors such that no two adjacent vertices of the graph are colored with the same color.

![Screenshot 2024-10-02 192021](https://github.com/user-attachments/assets/99d8154f-2811-4c9d-8096-c8fb5d1699be)

**Comment by AbhijitMotekar99** [comment]
Hey @Shubhanshu-1507
can you add the Hacktoberfest2024 and Hacktoberfest-accepted label please.

**Comment by Shubhanshu-1507** [comment]
> Hey @Shubhanshu-1507 can you add the Hacktoberfest2024 and Hacktoberfest-accepted label please.

Only merged Pull-requested are counted as contribution and not raising the issue in coment, so even if label this, it won't be marked as count , if you want this as contribution atleast provide solution or create PR with Solution to this issue.
