### ISSUE TITLE
Add C based Encryption Algorithms For more Security 

### ISSUE THREAD

**Issue by rudrakadel** [Shubhanshu-1507/Sourcecode#226]
To improve the security of the system, we need to implement a variety of encryption algorithms in C. These algorithms will provide additional layers of protection for sensitive data and will be crucial in securing communication, data storage, and processing. The following tasks should be completed:

Proposed Algorithms:
AES (Advanced Encryption Standard)

Implement the AES algorithm for secure symmetric encryption of data.
Support key sizes: 128, 192, and 256 bits.

RSA (Rivest–Shamir–Adleman)

Implement the RSA algorithm for secure asymmetric encryption and digital signatures.
Support key generation, encryption, and decryption.

SHA-256 (Secure Hash Algorithm)

Implement the SHA-256 hashing algorithm for secure message integrity.
Ensure compliance with the FIPS PUB 180-4 standard.
Diffie-Hellman Key Exchange

Implement the Diffie-Hellman algorithm for secure key exchange.
Provide functionality to generate public and private keys and exchange them securely.

**Comment by Shubhanshu-1507** [comment]
#242
