### ISSUE TITLE
Add cpp solutions for Placement questions.

### ISSUE THREAD

**Issue by Ritax2003** [Shubhanshu-1507/Sourcecode#233]
Hello as a fresher and currently a fourth year BTech CSE student , i want to contribute the questions which were asked in placement exams. For the hacktoberfest 2024 contribution.

**Comment by Shubhanshu-1507** [comment]
Go for it 👍

**Comment by Ritax2003** [comment]
will it be accepted by hacktoberfest?

**Comment by eeshsaxena** [comment]
Assign me this issue i will do it.
