### ISSUE TITLE
Add CPU Scheduling Algorithms (First-Come-First-Serve, Round Robin, etc.)

### ISSUE THREAD

**Issue by Singhal1808** [Shubhanshu-1507/Sourcecode#259]
I would like to contribute by implementing CPU scheduling algorithms in this project. Scheduling algorithms are critical in operating systems for process management and ensuring optimal CPU utilization. Here's a list of algorithms I propose to implement:

-> First-Come-First-Serve (FCFS): A non-preemptive scheduling algorithm where the process that arrives first gets executed first.
-> Round Robin (RR): A preemptive algorithm where each process is assigned a fixed time slot in a cyclic order.
-> Shortest Job Next (SJN): A non-preemptive algorithm where the process with the shortest execution time is executed first.
-> Priority Scheduling: Processes are executed based on their priority. Could be preemptive or non-preemptive.

Please assign this issue to me as I'd like to contribute this feature.

**Comment by eeshsaxena** [comment]
Assign me this issue i will do it.
