### ISSUE TITLE
Subarray Sum Equals K

### ISSUE THREAD

**Issue by Astordnomer** [Shubhanshu-1507/Sourcecode#269]
Using a Hash Map (Unordered Map) To Optimize The Search For Subarrays With a Sum Equal To k.
Can You Assign Me So.

**Comment by aditi-agrawal12** [comment]
Hello @Shubhanshu-1507 
we can do this using Prefix sum and hashmap , please assign this issue to me using hactoberfest label 
so that I can make my first ever opensource contribution 😊

**Comment by Dhruv-ag433** [comment]
This can be done by using the Prefix Sum and Hashmap, please assign this issue to me for the most  OPTIMAL SOLUTION there is.
