### ISSUE TITLE
Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by KamakshiOjha** [Shubhanshu-1507/Sourcecode#272]
Description : Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.

The overall run time complexity should be O(log (m+n)).

Language : JAVA

please assign me this issue under hacktoberfest2024.

**Comment by eeshsaxena** [comment]
Assign me this issue i will do it.

**Comment by iz-Manik** [comment]
Please assign this to me.
