### ISSUE TITLE
Kadane's Algorithm in CPP

### ISSUE THREAD

**Issue by rogerdemello** [Shubhanshu-1507/Sourcecode#280]

**Comment by Patilomkar282** [comment]
Hello @Shubhanshu-1507 

Basically the Kadane's Algorithm is finding the sub-array from given array such that it's sum is greatest than any other possible sub-array from given main array. It  need DP for solving this problem.

I would like to contribute to this problem.
Assign this issue to me.

Thank you.

**Comment by eeshsaxena** [comment]
Assign me this issue i will do it.

**Comment by Amangupta97656** [comment]
Assign me issue

**Comment by Roopun** [comment]
I want to resolve this @Shubhanshu-1507
