### ISSUE TITLE
Add Quick Sort in Java

### ISSUE THREAD

**Issue by DinkyRajpoot56** [Shubhanshu-1507/Sourcecode#393]

**Comment by DinkyRajpoot56** [comment]
QuickSort is a sorting algorithm based on the Divide and Conquer that picks an element as a pivot and partitions the given array around the picked pivot.

**Comment by Taj-2005** [comment]
please assign this task to me for hacktoberfest2024

**Comment by 0xSHSH** [comment]
Hey! @Shubhanshu-1507 can you assign me this issue.

**Comment by Shubhanshu-1507** [comment]
> Hey! @Shubhanshu-1507 can you assign me this issue. 

Bro repository got excluded, so if you want to contribute in hactoberfest , it won't count as contribution that's why I stopped assigning & accepting PR merged requests
